apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  namespace: default
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/target: "1"
        autoscaling.knative.dev/target-utilization-percentage: "100"
        autoscaling.knative.dev/target-burst-capacity: "-1"
    spec:
      containerConcurrency: 1
      containers:
        - image: crccheck/hello-world:latest # Stub image. See https://github.com/vhive-serverless/vhive/issues/68
          ports:
            - name: h2c # For GRPC support
              containerPort: 50051
          env:
            - name: GUEST_PORT # Port on which the firecracker-containerd container is accepting requests
              value: "50051"
            - name: GUEST_IMAGE # Container image to use for firecracker-containerd container
              value: "docker.io/zhaoshihan/pixels-worker-vhive-late:latest"
            - name: MINIO_ENDPOINT
              value: 
            - name: MINIO_ACCESS_KEY
              value: 
            - name: MINIO_SECRET_KEY
              value: 
            - name: MINIO_REGION
              value: 